[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/:asin"
  to = "/.netlify/functions/go"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/go"
  status = 200
