[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/go"
  status = 200

[[redirects]]
  from = "/create"
  to = "/create.html"
  status = 200
